name: sbom-analyzer
version: 1.0.0
description: |
  Analyzes Software Bill of Materials (SBOM) files to extract package information,
  verify repository status, and check for unmaintained dependencies.

  Efficiently processes large SBOMs with hundreds of packages in batches.

author: Kitty Team
license: MIT

variables:
  sbom_file: ""
  output_format: "markdown"
  current_offset: 0
  batch_size: 50
  all_batches: []
  total_analyzed: 0

tasks:
  - name: analyze_batch
    description: Analyze a batch of GitHub packages from SBOM
    tool: batch_analyze_github_packages
    input:
      file_path: "${sbom_file}"
      batch_size: ${batch_size}
      offset: ${current_offset}
    output: batch_result

  - name: evaluate_progress
    description: Decide if we need to continue
    prompt: |
      Based on the batch result, determine if we should continue processing more batches.

      has_more flag: ${batch_result.has_more}
      next_offset: ${batch_result.next_offset}

      If has_more is true, return:
      {"continue": true, "next_offset": ${batch_result.next_offset}, "reason": "More packages to process"}

      If has_more is false, return:
      {"continue": false, "reason": "All packages processed"}

      Return ONLY the JSON object, no markdown or code blocks.
    output: evaluation

  - name: generate_report
    description: Generate final comprehensive SBOM security report
    prompt: |
      Generate a comprehensive SBOM security report from the analysis results.

      ACCUMULATED PACKAGES (all iterations):
      ${all_batches}

      PURL STATISTICS (from SBOM):
      ${batch_result.purl_stats}

      TOTAL ANALYZED: ${total_analyzed}

      The all_batches array contains ALL analyzed packages from all iterations.
      Each package has: purl, owner, repo, status, stars, archived, last_commit_date,
      last_commit_sha, last_commit_sha_short, last_commit_message, license, etc.

      Use ALL packages in all_batches to generate comprehensive statistics.

      Analyze the data and format as markdown:

      # SBOM Security Analysis Report
      *Generated: <current date and time>*

      ## Executive Summary
      - **Total GitHub packages found**: ${batch_result.total_packages}
      - **Successfully analyzed**: ${total_analyzed}
      - **Failed/Unknown**: <count packages with status='unknown'>

      ## Package Statistics

      ### By Package Type (from SBOM)
      Analyze ${batch_result.purl_stats} and create table:
      | Type | Count | Description |
      |------|-------|-------------|
      | golang | X | Go modules |
      | npm | X | JavaScript packages |
      | apk | X | Alpine packages |
      | pypi | X | Python packages |
      | maven | X | Java packages |
      | ... | ... | ... |

      ### By Maintenance Status
      Analyze ALL packages in all_batches and count by status field:
      | Status | Count | Percentage |
      |--------|-------|------------|
      | ✅ Maintained | <count where status='maintained'> | <percent>% |
      | ⚠️ Stale (6-12mo) | <count where status='stale'> | <percent>% |
      | ❌ Unmaintained (12+mo) | <count where status='unmaintained'> | <percent>% |
      | 🗄️ Archived | <count where status='archived'> | <percent>% |
      | ❓ Unknown/Error | <count where status='unknown'> | <percent>% |

      ### By License
      Analyze all_batches and count by license field, show top 5:
      | License | Count |
      |---------|-------|
      | MIT | <count> |
      | Apache-2.0 | <count> |
      | ... | ... |

      ## ⚠️ Non-Active Projects

      ### Unmaintained Packages (12+ months without updates)
      Filter all_batches where status='unmaintained' and create table:
      | Package | Version | Last Commit | Stars | Status |
      |---------|---------|-------------|-------|--------|
      | [owner/repo](github_url) | version | SHA (date) | ⭐ count | months ago |

      ### Archived Packages
      Filter all_batches where archived=true and create table:
      | Package | Version | Last Commit | Stars |
      |---------|---------|-------------|-------|
      | [owner/repo](github_url) | version | SHA (date) | ⭐ count |

      ### Stale Packages (6-12 months without updates)
      Filter all_batches where status='stale' and create table:
      | Package | Version | Last Commit | Stars |
      |---------|---------|-------------|-------|
      | [owner/repo](github_url) | version | SHA (date) | ⭐ count |

      ## Top 10 Most Popular Packages
      Sort all_batches by stars descending, take top 10:
      | Rank | Package | Stars | Status | Last Update |
      |------|---------|-------|--------|-------------|
      | 1 | [owner/repo](github_url) | ⭐ count | status | date |

      ## Security Recommendations

      ### 🔴 Critical (Immediate Action Required)
      Analyze all_batches and list:
      - All archived packages (need replacement)
      - Unmaintained packages with >1000 stars (high-usage dependencies at risk)

      ### 🟡 Warning (Monitor Closely)
      Analyze all_batches and list:
      - Stale packages (6-12 months old) approaching unmaintained status
      - Packages with no license information

      ### 🟢 Good
      Calculate from all_batches:
      - X% of packages are actively maintained (<6 months)
      - Highlight well-maintained critical dependencies (high stars + maintained status)

      ## Overall Risk Assessment
      - **Risk Level**: Low/Medium/High (calculate based on percentages)
      - **Justification**: Based on counts of unmaintained/archived packages

      Use actual data from all_batches (${total_analyzed} packages). Be specific with numbers and dates.
    output: report
